#!/bin/bash


static=app/static
port=8000

if [[ "$VIRTUAL_ENV" != "" ]]; then
	pipenv shell
fi

if [[ oxytone != `basename $PWD` ]]; then
	exit 1
fi

set -eux

install_deps() {
	pipenv install & npm install & wait
}

init() {
	install_deps &&
	script seed & script chunkup & wait
}

css() {
	npx sass -Inode_modules $static:$static --update "$@"
}

js() {
	npx esbuild $static/reader.ts --outdir=$static \
		--bundle --target=es2020 --sourcemap "$@"
}

browsersync() {
	npx browser-sync start -w -f app/** \
		--proxy "localhost:$port" --no-open "$@"
}

app() {
	sanic app.main "$@"
}

watch() {
	css --watch &
	# watchmedo shell-command -p "*.ts" -c js -W $static &
	js --watch=forever &
	browsersync &
	app "$@"
}

test() {
	pytest "$@"
}

format() {
	black . "$@"
}

export_static() {
	wget -r -nH -P build --page-requisites --html-extension \
		localhost:$port "$@"
}

test_e2e() {
	export_static --spider -nd --quiet
}

script() {
	python -m scripts."$1"
}

sync_fs() {
	rsync -aP --delete --exclude-from=.rsyncignore \
		./ oxy:oxytone
}

deploy() {
	install_deps
	app
}

clean() {
	rm -f data/lsj.db
	rm -rf ${static}/**.{css,css.map,js,js.map}
	rm -rf data/treebanks/chunks/**
	rm -rf tmp/**
	rm -rf build/**
}

help() {
	compgen -A function
}

"${@:-watch}"
