#!/bin/bash

set -eu

static=app/static


if [[ -d .venv ]]; then
	. .venv/bin/activate
fi

set -x

deps() {
	python -m venv .venv
	. .venv/bin/activate
	pip install -r requirements.txt & npm install & wait
	script seed
	script chunkup
}

css() {
	npx sass -Inode_modules $static:$static "$@"
}

js() {
	npx esbuild $static/reader.ts --outdir=$static \
		--bundle --target=es2020 --sourcemap "$@"
}

browsersync() {
	npx browser-sync start -w -f app/** \
		--proxy 'localhost:5000' --no-open "$@"
}

app() {
	python -m app.main "$@"
}

watch() {
	css --watch &
	# watchmedo shell-command -p "*.ts" -c js -W $static &
	js --watch=forever & jspid=$!
	browsersync & bspid=$!
	app "$@"
	kill $jspid $bspid
}

test() {
	pytest "$@"
}

format() {
	black . "$@"
}

export_static() {
	wget -r -nH -P build --page-requisites --html-extension \
		localhost:5000 "$@"
}

test_e2e() {
	export_static --spider -nd --quiet
}

script() {
	python -m scripts."$1"
}

clean() {
	rm -f data/lsj.db
	rm -rf ${static}/**.{css,css.map,js,js.map}
	rm -rf data/treebanks/chunks/**
	rm -rf tmp/**
	rm -rf build/**
}


"${@:-watch}"