#!/bin/bash

src=app/src
static=app/static
port=8000
py="pipenv run"

if [[ oxytone != $(basename "$PWD") ]]; then
	exit 1
fi

set -eux

install_deps() {
	pipenv install & npm install & wait
}

init() {
	install_deps &&
	script seed & script chunkup & wait
}

assets() {
	css & js & wait
}

css() {
	npx sass -Inode_modules $src:$static --update "$@"
}

js() {
	npx tsc "$@"
}

bundle() {
	npx esbuild $src/reader.js --outfile=$static/reader.min.js \
		--bundle --format=esm --sourcemap "$@"
}

browsersync() {
	npx browser-sync start -w -f app/static/** templates/** \
		--proxy "localhost:$port" --no-open "$@"
}

app() {
	$py sanic app.main "$@"
}

watch() {
	browsersync &
	css --watch &
	js --watch &
	bundle --watch
}

test() {
	$py pytest "$@"
}

format() {
	$py black . "$@"
}

export_static() {
	wget -r -nH -P build --page-requisites --html-extension \
		localhost:$port "$@"
}

test_e2e() {
	export_static --spider -nd --quiet
}

script() {
	$py python -m scripts."$1"
}

sync_fs() {
	rsync -aP --delete --exclude-from=.rsyncignore \
		./ oxy:/var/www/oxytone
}

deploy() {
	install_deps
	assets
	bundle --minify
	sudo systemctl restart oxytone.service
}

clean() {
	rm -f data/lsj.db
	rm -rf $static/**.{css,css.map,js,js.map}
	rm -rf data/treebanks/chunks/**
	rm -rf tmp/**
	rm -rf build/**
}

help() {
	compgen -A function
}

"${@:-watch}"
